version: '3.1'

services:
  postgres:
    image: postgres:16
    container_name: CineRateDb
    restart: always
    environment:
      POSTGRES_DB: CineRateDb
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  pg_data:
